### ISSUE TITLE
Add D3.js to list of past workshops

### ISSUE THREAD

**Issue by fernandogelin** [dscov-tutorials/schedule_and_links#2]
Add "Basics of Data Visualization with D3.js" to list of previous workshops with link to Observable notebook: https://observablehq.com/@randallmorey/basics-of-data-visualization-with-d3-js
@mirestrepo

**Comment by fernandogelin** [comment]
March 21, 2019: Basics of Data Visualization with D3.js
-----
Presenter: Randall Morey
Related links: https://observablehq.com/@randallmorey/basics-of-data-visualization-with-d3-js

**Comment by fernandogelin** [comment]
@mcmcgrath13

**Comment by mcmcgrath13** [comment]
Done.
